language: node_js
node_js: stable
sudo: false

env:
  global:
    secure: "a5khJF7IdbDt2cT7xjlVpEglXeud5Ln+4AnfjOwR7hrcFnwY9s/fHDXRdNi/QdOUnl/2vFM86OXgyEVUOCnwvJAPHu5fw6nDfcj18CMDBUNBZvVXwEFCTJTjL8P+zTsGx5Sh8xmWo2s+eoPJiczcwtsk7XD9gMoTYrR5Us9KF/0="

addons:
  ssh_known_hosts: console.spec.whatwg.org

script:
- make deploy
